version: '3.9'

services:
    api:
      ports:
      - "8000:8000"
      volumes:
      - .:/app/src/
      environment:
        # Enables autoreload.
        FOODSHAREAPP_API_RELOAD: "True"
    client:
      build:
        target: dev
      volumes:
      - ./clientapp:/app
      # Avoid overwriting node_modules
      - /app/node_modules
      ports:
      - '${CLIENT_DEV_PORT}:${VUE_PORT}'
      # Run Vue dev server
      command: ["npm", "run", "serve"]
    db:
      ports:
      # Exposes application port.
      - "5432:5432"