services:
  api:
    ports:
      - "8000:8000"
    volumes:
      - .:/app/src
    environment:
      # Enables autoreload.
      FOODSHAREAPP_API_RELOAD: "True"
    ulimits:
      nofile:
        soft: 65536
        hard: 65536

  client:
    build:
      target: dev
    volumes:
      - ./clientapp:/app
      - /app/node_modules
    ports:
      - '${CLIENT_DEV_PORT}:${VUE_PORT}'
    environment:
    - CHOKIDAR_USEPOLLING=true
    - NODE_OPTIONS=--max-old-space-size=4096
    - NODE_ENV=development
    command: ["npm", "run", "serve"]
    ulimits:
      nofile:
        soft: 65536
        hard: 65536

  db:
    ports:
      - "5432:5432"
