name: Auto Assign Reviewers

on:
  pull_request:
    types: [opened]

jobs:
  add-reviewers:
    runs-on: ubuntu-latest
    steps:
      - name: Request Reviewers
        uses: peter-evans/auto-request-review@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          reviewers: alxxjohn
