name: Close Linked Issues

on:
  repository_dispatch:
    types: [circleci-pr-merged]  # Custom event triggered by CircleCI

jobs:
  close-linked-issues:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: read
    steps:
      - name: Extract Linked Issues
        id: extract_issue
        uses: actions/github-script@v7
        with:
          script: |
            const prNumber = ${{ github.event.client_payload.pull_request_number }};
            if (!prNumber) {
              console.log("No PR number received.");
              return;
            }

            const { data: pr } = await github.rest.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: prNumber
            });

            const issueRegex = /(?:Closes|Fixes|Resolves) #(\d+)/gi;
            let match;
            let issues = [];
            while ((match = issueRegex.exec(pr.body)) !== null) {
              issues.push(match[1]);
            }

            if (issues.length === 0) {
              console.log("No linked issues found.");
              return;
            }

            console.log(`Linked issues: ${issues.join(", ")}`);
            core.setOutput("issues", issues.join(" "));

      - name: Close Linked Issues
        if: steps.extract_issue.outputs.issues != ''
        uses: actions/github-script@v7
        with:
          script: |
            const issues = "${{ steps.extract_issue.outputs.issues }}".split(" ");
            for (const issue_number of issues) {
              await github.rest.issues.update({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: parseInt(issue_number, 10),
                state: "closed"
              });
            }
