name: Front End Tests

on:
  pull_request:
    types: [opened, edited]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4 

      - name: Debug package-lock.json location
        run: find . -name "package-lock.json" || echo "No package-lock.json found"

      - name: Generate package-lock.json if missing
        run: |
          if [ ! -f "clientapp/package-lock.json" ]; then
            echo "No package-lock.json found. Generating..."
            npm install --package-lock-only
          else
            echo "package-lock.json already exists."
          fi
        working-directory: clientapp  

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'
          cache-dependency-path: clientapp/package-lock.json  

      - name: Install Dependencies
        run: npm install
        working-directory: clientapp

      - name: Run Tests
        run: npm test
        working-directory: clientapp

      - name: Ensure test-results directory exists
        run: mkdir -p test-results

      - name: Upload Test Reports
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: test-results/
