name: PR Title Check

on:
  pull_request:
    types: [opened, edited]

jobs:
  check-title:
    runs-on: ubuntu-latest
    steps:
      - name: Ensure PR title follows format
        uses: amannn/action-semantic-pull-request@v5
        with:
          types: |
            feat
            fix
            chore
            docs
            refactor
            style
            test
          subjectPattern: "^(\\[JIRA-\\d+\\]) .+$"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
